name: C/C++ CI

on:
  push:
    branches: [ Nethunter ]
  pull_request:
    branches: [ Nethunter ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./cronos.sh
    - name: make
      run: n
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
